AWSTemplateFormatVersion: '2010-09-09'
Description: Birthday Present Tracker API

# Inputs provided to template on creation / update
Parameters:
  # Default username for db, allow user to provide if they wish to have a different one in place
  # Validation in place to satisfy db format
  DBUsername:
    Description: Username used in interactions with RDS instance
    Type: String
    Default: admin
    MinLength: 1
    MaxLength: 16
    AllowedPattern: '^[a-zA-Z][a-zA-Z0-9_]*$'
    ConstraintDescription: "Must start with a letter. Only alphanumeric characters, underscores permitted"
  # User must provide password to be used for RDS db interaction, satisfies RDS db constraints
  # Note NoEcho to prevent this being outputted in logs etc.
  DBPassword:
    Description: Password used for user to access RDS database instance
    Type: String
    NoEcho: true
    MinLength: 8
    MaxLength: 40
    AllowedPattern: '^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@#$_!%*?&\-])[A-Za-z\d@#$_!%*?&\-]{8,40}$'
    ConstraintDescription: "8-40 characters, must contain uppercase, lowercase, number, and one special char from (@#$_!%*?&-)"
  # Also allow custom db name, default if not provided
  DBName:
    Description: Name of the RDS database
    Type: String
    Default: birthdayDb
    AllowedPattern: '^[a-zA-Z0-9_]+$'
    ConstraintDescription: "Only alphanumeric characters, underscores permitted"
  # This is for lambda power tools, default to 3.12, allow other earlier versions if user wants one of those
  LambdaRuntime:
    Description: Python version in use
    Type: String
    Default: python3.12
    AllowedValues:
      - python3.9
      - python3.10
      - python3.11
      - python3.12
  # Also related to lambda power tools, can provision them via windows / mac
  LambdaArchitecture:
    Description: OS used for Lambda Powertools
    Type: String
    Default: x86_64
    AllowedValues:
      - x86_64
      - arm64
  # S3 bucket name where the code for lambda is to be stored
  # Github pipeline creates this before this template is run
  # If run from aws console, assumption that user has created bucket before provisioning this template
  LambdaCodeBucket:
    Description: Name of S3 bucket where Lambda deployment package is stored
    Type: String
    MinLength: 3
    MaxLength: 63
    AllowedPattern: '^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$'
    ConstraintDescription: "Must be valid s3 bucket name - lowercase letters, numbers, full stops, dashes"
  # File name where code is stored within s3 bucket
  LambdaCodeBucketKey:
    Description: File name within s3 bucket for the Lambda deployment python package
    Type: String
    MinLength: 1
    AllowedPattern: '^(?!/)[^\s]+$'
    ConstraintDescription: "Cannot be empty, cannot start with /, spaces not allowed"
  # Support for different environments (dev / prod) to simulate different conditions between envs in template (e.g. retention policies etc)
  EnvironmentName:
    Description: Environment in use for API Gateway (Dev / Prod)
    Type: String
    AllowedValues:
      - Dev
      - Prod
  # Used in dev environment to ensure unique titles for resources (avoids clashes on multiple runs)
  ResourceSuffix:
    Description: Append this to resource names in dev env to avoid clashes between dev and prod envs
    Type: String
    Default: ""
    AllowedPattern: '^[a-zA-Z0-9-]*$'
    ConstraintDescription: "Only letters, numbers, dashes allowed"
  # This is used to ensure API gateway provisions on any change (as otherwise, it doesn't re-provision)
  DeploymentId:
    Description: Versioning to force API deployment on each push
    Type: String
    Default: "1"
    AllowedPattern: '^[0-9]+$'
    ConstraintDescription: "Must be numeric"

# Define a condition to determine if environment is dev / prod (True if Dev, False if Prod)
Conditions:
  IsDevEnvironment:
    Fn::Equals:
      - !Ref EnvironmentName
      - Dev

# Define a mapping for python versions to lambda tool version string format
# Also define a lowercase mapping for environments
Mappings:
  PythonRuntimeToLayer:
    python3.9:
      Layer: python39
    python3.10: 
      Layer: python310
    python3.11: 
      Layer: python311
    python3.12: 
      Layer: python312
  LowercaseEnvironment:
    Dev:
      Name: dev
    Prod:
      Name: prod


# Define resources in use within the template
Resources:
  # Create private VPC, note /16 subnet
  BirthdayPresentTrackerVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
  
  # First subnet - slash 24 subnet
  # Note first availability zone in current region selected
  BirthdayPresentTrackerSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: !Ref "AWS::Region"
      VpcId: !Ref BirthdayPresentTrackerVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
  
  # Second subnet - slash 24 subnet
  # Note second availability zone in current region selected
  BirthdayPresentTrackerSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs: !Ref "AWS::Region"
      VpcId: !Ref BirthdayPresentTrackerVPC
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: true
  
  # Subnet group with both subnets included
  BirthdayPresentTrackerDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for Birthday Present Tracker RDS Instance
      SubnetIds:
        - !Ref BirthdayPresentTrackerSubnetA
        - !Ref BirthdayPresentTrackerSubnetB
  
  # Security group for Lambda
  BirthdayPresentTrackerLambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Lambda security group with outbound access
      VpcId: !Ref BirthdayPresentTrackerVPC
  
  # Define egress rules for lambda (note anything allowed outbound)
  BirthdayPresentTrackerLambdaSecurityGroupEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref BirthdayPresentTrackerLambdaSecurityGroup
      IpProtocol: -1
      CidrIp: 0.0.0.0/0
  
  # Security group for RDS database
  BirthdayPresentTrackerRDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for RDS MySQL
      VpcId: !Ref BirthdayPresentTrackerVPC
  
  # Limit ingress to only port 3306 (MySql) for resources with Lambda security group
  BirthdayPresentTrackerRDSIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref BirthdayPresentTrackerRDSSecurityGroup
      IpProtocol: tcp
      FromPort: 3306
      ToPort: 3306
      SourceSecurityGroupId: !Ref BirthdayPresentTrackerLambdaSecurityGroup
  
  # Security group for Secret Manager VPC endpoint
  BirthdayPresentTrackerSecretsManagerEndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for Secrets Manager VPC Endpoint
      VpcId: !Ref BirthdayPresentTrackerVPC

  # Ingress only allows port 443 from resources with lambda security group attached
  BirthdayPresentTrackerSecretsManagerIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref BirthdayPresentTrackerSecretsManagerEndpointSecurityGroup
      IpProtocol: tcp
      FromPort: 443
      ToPort: 443
      SourceSecurityGroupId: !Ref BirthdayPresentTrackerLambdaSecurityGroup
  
  # DB secret which is stored in secrets manager service
  # Note retention if Prod, deletion if Dev
  # Stores the db credentials securely
  BirthdayPresentTrackerDBSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy:
      Fn::If:
        - IsDevEnvironment
        - Delete
        - Retain
    UpdateReplacePolicy:
      Fn::If:
        - IsDevEnvironment
        - Delete
        - Retain
    Properties:
      Name:
        Fn::Sub:
          - "BirthdayPresentTrackerDBSecret${Suffix}"
          - Suffix:
              Fn::If:
                - IsDevEnvironment
                - !Ref ResourceSuffix
                - ""
      Description: RDS credentials for Birthday Present Tracker DB in use for API
      SecretString: !Sub '{"username": "${DBUsername}", "password": "${DBPassword}", "dbname": "${DBName}"}'
  

  # VPC endpoint for secrets manager service
  # Needed to allow lambda to access secrets manager service as within private VPC
  # Note security group attached here to limit services
  BirthdayPresentTrackerSecretsManagerEndpoint:
    Type: AWS::EC2::VPCEndpoint
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      VpcId: !Ref BirthdayPresentTrackerVPC
      ServiceName: !Sub com.amazonaws.${AWS::Region}.secretsmanager
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      SubnetIds:
        - !Ref BirthdayPresentTrackerSubnetA
        - !Ref BirthdayPresentTrackerSubnetB
      SecurityGroupIds:
        - !Ref BirthdayPresentTrackerSecretsManagerEndpointSecurityGroup
  
  # RDS db instance
  # Note depends on to ensure that secrets manager work has been completed before referencing
  # Again different retention and deletion policies based on environment
  BirthdayPresentTrackerRDSInstance:
    Type: AWS::RDS::DBInstance
    DependsOn: 
      - BirthdayPresentTrackerSecretsManagerEndpoint
      - BirthdayPresentTrackerDBSecret
    DeletionPolicy:
      Fn::If:
        - IsDevEnvironment
        - Delete
        - Retain
    UpdateReplacePolicy:
      Fn::If:
        - IsDevEnvironment
        - Delete
        - Retain
    Properties:
      DBInstanceIdentifier: 
        Fn::Sub:
          - "birthday-present-tracker-database${Suffix}"
          - Suffix:
              Fn::If:
                - IsDevEnvironment
                - !Ref ResourceSuffix
                - ""
      DBSubnetGroupName: !Ref BirthdayPresentTrackerDBSubnetGroup
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: mysql
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Sub '{{resolve:secretsmanager:BirthdayPresentTrackerDBSecret${ResourceSuffix}:SecretString:password}}'
      DBName: !Ref DBName
      VPCSecurityGroups:
        - !GetAtt BirthdayPresentTrackerRDSSecurityGroup.GroupId
      PubliclyAccessible: false
      # This is disabled for quicker testing
      BackupRetentionPeriod: 0
      DeletionProtection: false
      MultiAZ: false
  
  # Custom role needed for lambda to access services
  # Keep basic role as this includes Cloudwatch logs
  # Needs VPC access role as within a VPC
  BirthdayPresentTrackerLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 
        Fn::Sub:
        - "BirthdayPresentTrackerLambdaExecutionRole${Suffix}"
        - Suffix:
            Fn::If:
              - IsDevEnvironment
              - !Ref ResourceSuffix
              - ""
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: LambdaSecretsAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref BirthdayPresentTrackerDBSecret

  # Lambda where Python code is executed
  # Note use of Layers to load in Lambda power tools (metrics, logging, tracing)
  # This is also where files are loaded from s3 for accessing the Python code 
  BirthdayPresentTrackerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: 
        Fn::Sub: 
          - "BirthdayPresentTrackerApiHandler${Suffix}"
          - Suffix:
              Fn::If:
                - IsDevEnvironment
                - !Ref ResourceSuffix
                - ""
      Runtime: !Ref LambdaRuntime
      Handler: index.lambda_handler
      Role: !GetAtt BirthdayPresentTrackerLambdaRole.Arn
      VpcConfig:
        SubnetIds:
          - !Ref BirthdayPresentTrackerSubnetA
          - !Ref BirthdayPresentTrackerSubnetB
        SecurityGroupIds:
          - !Ref BirthdayPresentTrackerLambdaSecurityGroup
      Timeout: 15
      Layers:
          - Fn::Sub:
            - arn:${Partition}:lambda:${Region}:017000801446:layer:AWSLambdaPowertoolsPythonV3-${Layer}-${Architecture}:18
            - Partition: !Ref AWS::Partition
              Region: !Ref AWS::Region
              Layer: !FindInMap [PythonRuntimeToLayer, !Ref LambdaRuntime, Layer]
              Architecture: !Ref LambdaArchitecture
      Environment:
        Variables:
          DB_HOST: !GetAtt BirthdayPresentTrackerRDSInstance.Endpoint.Address
          DB_SECRET_NAME: !Ref BirthdayPresentTrackerDBSecret
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Ref LambdaCodeBucketKey
  
  # Rest API Gateway instance
  BirthdayPresentTrackerApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: 
        Fn::Sub:
          - "BirthdayPresentTrackerApi${Suffix}"
          - Suffix:
              Fn::If:
                - IsDevEnvironment
                - !Ref ResourceSuffix
                - ""
      Description: API returning dummy data from db
      EndpointConfiguration:
        Types: ["REGIONAL"]
  
  # Api gateway resource which maps the API path
  BirthdayPresentTrackerResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref BirthdayPresentTrackerApi
      ParentId: !GetAtt BirthdayPresentTrackerApi.RootResourceId
      PathPart: birthdays
  
  # GET method for API
  # Note the proxy call to trigger the Lambda
  BirthdayPresentTrackerGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref BirthdayPresentTrackerApi
      ResourceId: !Ref BirthdayPresentTrackerResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri:
          Fn::Sub:
          - arn:${AWS::Partition}:apigateway:${Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations
          - Region: !Ref "AWS::Region"
            LambdaArn: !GetAtt BirthdayPresentTrackerLambda.Arn
  
  # PUT method for API
  # Note the proxy call to trigger the Lambda
  BirthdayPresentTrackerPutMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref BirthdayPresentTrackerApi
      ResourceId: !Ref BirthdayPresentTrackerResource
      HttpMethod: PUT
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri:
          Fn::Sub:
          - arn:${AWS::Partition}:apigateway:${Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations
          - Region: !Ref "AWS::Region"
            LambdaArn: !GetAtt BirthdayPresentTrackerLambda.Arn
  
  # POST method for API
  # Note the proxy call to trigger the Lambda
  BirthdayPresentTrackerPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref BirthdayPresentTrackerApi
      ResourceId: !Ref BirthdayPresentTrackerResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri:
          Fn::Sub:
          - arn:${AWS::Partition}:apigateway:${Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations
          - Region: !Ref "AWS::Region"
            LambdaArn: !GetAtt BirthdayPresentTrackerLambda.Arn

  # DELETE method for API
  # Note the proxy call to trigger the Lambda
  BirthdayPresentTrackerDeleteMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref BirthdayPresentTrackerApi
      ResourceId: !Ref BirthdayPresentTrackerResource
      HttpMethod: DELETE
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri:
          Fn::Sub:
          - arn:${AWS::Partition}:apigateway:${Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations
          - Region: !Ref "AWS::Region"
            LambdaArn: !GetAtt BirthdayPresentTrackerLambda.Arn
  
  # Add permission to trigger the lambda from the API
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref BirthdayPresentTrackerLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${BirthdayPresentTrackerApi}/*/*"
  
  # Deploy the API with all methods attached
  BirthdayPresentTrackerApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - BirthdayPresentTrackerGetMethod
      - BirthdayPresentTrackerPostMethod
      - BirthdayPresentTrackerPutMethod
      - BirthdayPresentTrackerDeleteMethod
    Properties:
      RestApiId: !Ref BirthdayPresentTrackerApi
      StageName: !FindInMap [LowercaseEnvironment, !Ref EnvironmentName, Name]
      Description: !Sub "Deployed with descriptor: ${DeploymentId}"

# Define outputs on completion of provisioning, currently just output the api endpoint url for testing
# Note substitution within url, dev / prod used depending on environment
Outputs:
  ApiEndpoint:
    Description: "Endpoint URL for API"
    Value: 
      Fn::Sub:
      - "https://${ApiId}.execute-api.${Region}.amazonaws.com/${Env}/birthdays"
      - ApiId: !Ref BirthdayPresentTrackerApi
        Region: !Ref "AWS::Region"
        Env: !FindInMap [LowercaseEnvironment, !Ref EnvironmentName, Name]