name: Deploy Birthday Present Tracker API on AWS

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, closed]

env:
  S3_BUCKET_NAME: birthday-present-tracker-lambda-deployment-bucket
  LAMBDA_ZIP_FILE: birthday_present_lambda.zip

jobs:
  deploy_on_pull_request:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set ENV variables
        id: set_pr_variables
        run: |
          PR_NUMBER="${{ github.event.pull_request.number || github.event.number }}"
          echo "STACK_NAME=BirthdayPresentTracker-PR-$PR_NUMBER" >> $GITHUB_ENV
          echo "CLOUD_ENVIRONMENT=Staging-$PR_NUMBER" >> $GITHUB_ENV
      - name: Deploy stack
        if: github.event.action == 'opened' || github.event.action == 'synchronize'
        uses: ./.github/workflows/deploy-lambda.yml
        with:
          stack_name: ${{env.STACK_NAME}}
          environment: ${{env.CLOUD_ENVIRONMENT}}
          s3_bucket_name: ${{env.S3_BUCKET_NAME}}
          lambda_zip_file: ${{env.LAMBDA_ZIP_FILE}}
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          DB_ADMIN_PASSWORD: ${{ secrets.DB_ADMIN_PASSWORD }}

      - name: Configure AWS credentials
        if: github.event.action == 'closed'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Execute Stack Deletion
        if: github.event.action == 'closed'
        run: |
          echo "Deleting stack ${{ env.STACK_NAME }}"
          aws cloudformation delete-stack --stack-name ${{ env.STACK_NAME }}
          aws cloudformation wait stack-delete-complete --stack-name ${{ env.STACK_NAME }}

  deploy_to_production:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to prod
        uses: ./.github/workflows/deploy-lambda.yml
        with:
          stack_name: BirthdayPresentTracker-Prod
          environment: Prod
          s3_bucket_name: ${{env.S3_BUCKET_NAME}}
          lambda_zip_file: ${{env.LAMBDA_ZIP_FILE}}
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          DB_ADMIN_PASSWORD: ${{ secrets.DB_ADMIN_PASSWORD }}
